"""add_analysis_history_and_api_usage_tables

Revision ID: 73d2de898202
Revises: add_active_20251120
Create Date: 2025-12-01 15:45:00.212404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73d2de898202'
down_revision: Union[str, Sequence[str], None] = 'add_active_20251120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_length', sa.Integer(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_analysis_type'), 'analysis_history', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_history_created_at'), 'analysis_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_analysis_history_user_id'), 'analysis_history', ['user_id'], unique=False)
    op.create_table('api_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('grammar_count', sa.Integer(), nullable=False),
    sa.Column('plagiarism_count', sa.Integer(), nullable=False),
    sa.Column('similarity_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_index(op.f('ix_api_usage_date'), 'api_usage', ['date'], unique=False)
    op.create_index(op.f('ix_api_usage_user_id'), 'api_usage', ['user_id'], unique=False)
    op.drop_table('analysisrecord')
    op.create_index(op.f('ix_user_active'), 'user', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_active'), table_name='user')
    op.create_table('analysisrecord',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('ai_probability', sa.FLOAT(), nullable=False),
    sa.Column('kobert_score', sa.FLOAT(), nullable=False),
    sa.Column('similarity_score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=True),
    sa.Column('perplexity_score', sa.FLOAT(), nullable=True),
    sa.Column('burstiness_score', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_api_usage_user_id'), table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_date'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_analysis_history_user_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_created_at'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_analysis_type'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
