"""Add analysis_config table

Revision ID: bf4638d3da59
Revises: 6de745c9587c
Create Date: 2025-11-04 16:38:04.583172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf4638d3da59'
down_revision: Union[str, Sequence[str], None] = '6de745c9587c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_config',
    sa.Column('text_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sbert_weight', sa.Float(), nullable=False),
    sa.Column('kobert_weight', sa.Float(), nullable=False),
    sa.Column('perplexity_weight', sa.Float(), nullable=False),
    sa.Column('burstiness_weight', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_config_text_type'), 'analysis_config', ['text_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_config_text_type'), table_name='analysis_config')
    op.drop_table('analysis_config')
    # ### end Alembic commands ###
